### PR TITLE
Backport 1.18.2 Backport to 1.17.1

### PR DESCRIPTION
**Pull request by thecatcore**
Everything seems to work as intended.

Ugh I don't know which branch to target.

### CODE REVIEW

**Comment by thecatcore** [comment]
Also, I'm not sure if the mod version should be 1.11.3 too or 1.9.9 in this case.

**Comment by HyperPigeon** [comment]
I can't merge this pr w/o overwriting my 1.18.2 backport. I can create a copy of the 1.18.2 backport branch renamed to 1.17.1_backport and you can PR into that instead.

**Comment by thecatcore** [comment]
👍

**Comment by thecatcore** [comment]
Changed target branch.

**Pull request merged**
